on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-and-patch:
    runs-on: ubuntu-latest

    steps:

    # Step 0: Set git identity
    - name: Set git config
      run: |
        git config --global user.email "vincetheprogrammer@gmail.com"
        git config --global user.name "vinceTheProgrammer"

    # Step 1: Check out this repository
    - name: Checkout patch repo
      uses: actions/checkout@v4
      with:
        path: main

    # Step 2: Check out the source (upstream) repository
    - name: Check out upstream repo
      uses: actions/checkout@v4
      with:
        repository: cinnyapp/cinny
        ref: dev
        path: './cinny'

    # Step 3: Apply the patch from your repository
    - name: Apply custom patch
      working-directory: ${{ github.workspace }}/cinny
      run: |
        git apply --whitespace=fix ${{ github.workspace }}/main/dark-theme.patch
        git add .
        git commit -m "Apply custom patch"

    # Step 4: Install dependencies
    - name: Install dependencies
      working-directory: ${{ github.workspace }}/cinny
      run: npm ci

    # Step 5: Build the project
    - name: Build
      working-directory: ${{ github.workspace }}/cinny
      run: npm run build

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ../cinny/dist